name = "scholarpath"
compatibility_date = "2024-01-01"
type = "webpack"
account_id = "c0d8097d676db943630ce9bd340a70fd"
workers_dev = true

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
workers_dev = false
vars = { APP_ENV = "production", APP_DEBUG = "false" }
route = "scholarpath.pages.dev/*"

[build]
command = """
apt-get update && apt-get install -y php8.1-cli php8.1-mysql php8.1-zip php8.1-gd php8.1-mbstring php8.1-curl php8.1-xml php8.1-bcmath
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
composer install --no-dev --optimize-autoloader
npm install
npm run build
php artisan config:cache
"""
output_dir = "public"

[build.environment]
NODE_VERSION = "16"
PHP_VERSION = "8.1"
